# Generated by Django 2.2.3 on 2019-07-29 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authore',
            new_name='author',
        ),
    ]
