# Generated by Django 2.2.1 on 2019-06-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_slug',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
