# Generated by Django 2.2.1 on 2019-06-02 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogpost_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 14, 42, 26, 829118), verbose_name='date published'),
        ),
    ]
