# Generated by Django 2.2.1 on 2019-06-02 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190602_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 14, 57, 16, 253426), verbose_name='date published'),
        ),
    ]
